language: java

jdk:
  - oraclejdk7

branches:
  except:
    - gh-pages

before_install:
  mvn clean

install: mvn install -DskipTests=true && mvn clean

notifications:
  email:
    recipients:
      - dev@tradehero.mobi
    on_success: change
    on_failure: always
